### ISSUE TITLE
Version 1.2.0 has bug

### ISSUE THREAD

**Issue by ArtemProkopenko** [michaeldyrynda/laravel-nullable-fields#12]
I have field phone in my model with following content "8(909)779-03-12". Of course this field mark as Nullable.
I run following code
`
$user = User::find(9);
$user->save();
var_dump($user->phone);
`
And I getting following result: string(17) ""8(909)779-03-12"". You can see than we have here quotes inside string. So, I run code again and getting following result: string(21) ""\"8(909)779-03-12\""".

If I done downgrade to version 1.1.0 then this bug is disabled.

p.s. sorry for my bad English.

**Comment by michaeldyrynda** [comment]
Are you actually storing the `"` in your field? Does this field have a mutator set? Are you still experiencing this in 1.2.1?

**Comment by ArtemProkopenko** [comment]
Hi michaeldyrynda, 
No, I don't added the " to phone string and it don't exist in the original field.
I don't check it with 1.2.1, but I still experiencing this in dev-master.

**Comment by ArtemProkopenko** [comment]
Hello michaeldyrynda,
No, I don't added the " to phone string and it don't exist in the original field.
I checked 1.2.1 (master) and it work fine (without issue). But I don't can get 1.2.1 by packagist :(

**Comment by michaeldyrynda** [comment]
Is there a mutator for that attribute?

I have a rough idea of what the issue might be, but I won't get a chance to look at it properly until tomorrow. If you could submit a PR with a failing test and some sample code, that'll give me a starting point to work from.
