### ISSUE TITLE
[5.3] getAttributes must have a parameter

### ISSUE THREAD

**Issue by LimitTech** [michaeldyrynda/laravel-nullable-fields#15]
```
/**
 * Get all of the current attributes on the model.
 *
 * @return array
 */
abstract public function getAttributes(**$keys = []**);
```

**Comment by michaeldyrynda** [comment]
I'm on holiday at the moment, is this something that can wait, or that you can submit a PR for?

I think it may be time to tag a new make version of this package.

**Comment by LimitTech** [comment]
This change has been reverted in v5.3.18: https://github.com/laravel/framework/pull/15722

So nothing to do at this moment.

Thanks!
