### ISSUE TITLE
Redundancy

### ISSUE THREAD

**Issue by kobykorman** [michaeldyrynda/laravel-nullable-fields#22]
Hey,

Not an issue per se, but I was wondering if there's any use case for this package when using the new `ConvertEmptyStringsToNull` middleware?

The conversion is obviously done earlier, when the request is incoming, rather than on a model's event, but what's left for the trait to do then?

**Comment by michaeldyrynda** [comment]
I suppose it's still useful if you're manipulating the model outside of the request lifecycle, perhaps you're fetching something from an external API via a scheduled command, for example.

Other than that, I'm not too sure if I'm honest. The package certainly works with 5.4, but beyond that, I've not had a chance to play with it directly yet.

Once I've had a chance to play in greater detail, it may be that I just add a note to the README about using the nullable middleware during the request lifecycle.

**Comment by kobykorman** [comment]
Good point. Thanks for the input.

On a side note, I took inspiration from your/Taylor's work and created a UserStamps trait I'd like to release when I have time (similar concept to timestamps, only for `created_by`, `updated_by`, `deleted_by`). Would be interesting to get your review / thoughts when I do.
