### ISSUE TITLE
Why not with setters?

### ISSUE THREAD

**Issue by rudiedirkx** [michaeldyrynda/laravel-nullable-fields#28]
Just a question. This trait would be super useful if it immediately checked nullability (totally a word) when the attribute is set, instead of waiting for `saving`. If it immediately checks, you can use `isDirty()` and `getDirty()` more predictably between `fill()` and `save()`. (Doesn't help much if you only `$model->update()`.)

I'm having to `$this->fireModelEvent('saving');` after `$model->fill()` to trigger nullables to get a useful `getDirty()`, which makes me very very uncomfortable.

**Comment by michaeldyrynda** [comment]
How do you propose this to work? Wouldn't you need to create a setter for each field you want to check `null` for?

**Comment by rudiedirkx** [comment]
I use this trait in my base model for all nullifying/nullabilizing/nullization:

```
trait NullifiesAttributes {

	protected $nullable = [];

	public function setAttribute($key, $value) {
		$this->maybeNullifyAttribute($key, $value);

		return parent::setAttribute($key, $value);
	}

	public function maybeNullifyAttribute($key, &$value) {
		if ($this->isNullifiedAttribute($key)) {
			$value = $this->nullifyAttribute($key, $value);
		}
		return $value;
	}

	public function isNullifiedAttribute($key) {
		return isset($this->nullable[$key]) || in_array($key, $this->nullable, true);
	}

	public function nullifyAttribute($key, $value) {
		$nulls = $this->nullable[$key] ?? [''];
		return in_array($value, $nulls, true) ? null : $value;
	}

}
```

and this in specific models:

```
	const CONTACT_NONE = '-1';
	protected $nullable = [
		'subtype',
		'contact_id' => ['', self::CONTACT_NONE],
	];
```

So I can even choose which exact values must be converted to null. `subtype` only for empty string, `contact_id` also for `'-1'`.

**Comment by michaeldyrynda** [comment]
I think I'm going to leave this out for now.

I'm a little dubious about overriding any of Eloquent's methods  at the package level as that can lead to unpredictability for package consumers when they're expecting Laravel's methods to be behaving a certain way and they're being tampered with on the fly.

**Comment by rudiedirkx** [comment]
The Laravel method is still always called. The only conflict is with other packages that use the same trick. If 2 packages override `setAttribute()`, it's panic and mayhem, but it still always calls Laravel's `setAttribute()`.

**Comment by michaeldyrynda** [comment]
Sorry, I understand that, but to clarify that means we need to always keep tabs on the Laravel method and if it ever changes we need to follow suit.

I'm _always_ cautious about doing anything that overrides an Eloquent method then calls the parent. I've been bitten by it too many times in the past, and prefer to avoid doing it where possible.

**Comment by rudiedirkx** [comment]
Fair enough. Using the events API is always safer, I agree.
