### ISSUE TITLE
Attributes with a mutator are mutated twice

### ISSUE THREAD

**Issue by JacobBennett** [michaeldyrynda/laravel-nullable-fields#3]
because you are using the `setAttribute` method, values are being mutated once during that, and again before being persisted. This one bit me today :) 

Think there is a pretty simple solution that I can submit a PR for.

**Comment by michaeldyrynda** [comment]
Thanks man! I did actually get hit by a similar `setAttribute` issue recently where I was using it inside a  `setPasswordAttribute` mutator (running `bcrypt`) and found myself in an infinite loop!

If it's not too much trouble, could you submit the PR? If not, I'll have a look at this tonight :)
