### ISSUE TITLE
Nullable fields can't handle an array

### ISSUE THREAD

**Issue by JacobBennett** [michaeldyrynda/laravel-nullable-fields#4]
When trying to pass an array through as a nullable field, the `nullIfEmpty` method fails while trying to trim the array. Planning to fix this in a PR as well.

**Comment by michaeldyrynda** [comment]
What's the use case for this? Is this for when you're passing a field through that is cast to JSON, which you want to be `null` if the attribute is `[]`?

**Comment by JacobBennett** [comment]
Exactly. So like a multiple select input. Although actually after investigating this, a multiple select with nothing selected won't even be a part of the $request object so it shouldn't matter either way. In any case, array values fail when trying to be used as a nullable field. At the least it would be nice to have an exception thrown for array types.

**Comment by samwilson** [comment]
I'm getting this error also.

```
[ErrorException] trim() expects parameter 1 to be string, array given
\vendor\iatstuti\laravel-nullable-fields\src\NullableFields.php:44
```

Should it instead be e.g.:

``` php
return (empty($value) || trim($value) === '') ? null : $value;
```

?

**Comment by michaeldyrynda** [comment]
Hey @JacobBennett, @samwilson I've done a fair bit of work on this today adding array handling and finally figuring out how to unit test the functionality.

I'd appreciate if you could have a look and see if you think I've taken the right approach, or if you think there's something you'd change or do differently.

Getting around the array-to-JSON casting was an interesting one!

**Comment by JacobBennett** [comment]
Awesomene! I'll try to take a look at it tonight. Happens to be one of my favorite packages so would love to help. 

Jake Bennett

On Wed, Jan 20, 2016 at 6:45 PM -0800, "Michael Dyrynda" notifications@github.com wrote:

Hey @JacobBennett, @samwilson I've done a fair bit of work on this today adding array handling and finally figuring out how to unit test the functionality.

I'd appreciate if you could have a look and see if you think I've taken the right approach, or if you think there's something you'd change or do differently.

Getting around the array-to-JSON casting was an interesting one!

**Comment by samwilson** [comment]
Thanks @deringer looks good!
